import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser = await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
const page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const save=async()=>JSON.parse(await page.evaluate(()=>localStorage.getItem('road-haven-save-v1')));
const close=async()=>page.locator('#modal-root [data-close]').click();
const farm=async()=>page.locator('.scene-zones [data-open="farm"]').click();
const chore=async(button,assertNotApplied)=>{
 await button.click();
 assert.equal(await page.locator('#app').getAttribute('aria-busy'),'true');
 if(assertNotApplied)await assertNotApplied();
 await page.clock.runFor(1600);
 assert.equal(await page.locator('#app').getAttribute('aria-busy'),'true');
 await page.clock.runFor(5500);
 assert.equal(await page.locator('#app').getAttribute('aria-busy'),null);
};
try {
 await page.clock.install({time:new Date('2026-10-08T02:00:00Z')});
 await page.clock.pauseAt(new Date('2026-10-08T02:00:00Z'));
 await page.goto(process.env.TEST_BASE_URL||'http://127.0.0.1:5173');
 await page.getByRole('button',{name:'남자 생존자'}).click();
 await page.getByLabel('어떤 이름으로 불러 드릴까요?').fill('노을');
 await page.getByRole('button',{name:'우리집에서 시작하기'}).click();
 assert.equal((await save()).gender,'male');assert.equal((await save()).name,'노을');
 await page.getByRole('button',{name:'시간 일시정지',exact:true}).click();
 await farm();const before=await save();
 await chore(page.getByRole('button',{name:'수확하기',exact:true}),async()=>assert.equal((await save()).stats.harvests,before.stats.harvests));
 assert.equal((await save()).stats.harvests,before.stats.harvests+1);
 await farm();await chore(page.getByRole('button',{name:'씨앗 심기',exact:true}).first());
 await farm();await chore(page.getByRole('button',{name:'물 주기',exact:true}).first());
 assert.ok((await save()).plots[0].watered);
 await page.getByRole('button',{name:/트럭 확장/}).click();
 await chore(page.getByRole('button',{name:'데크 확장하기',exact:true}),async()=>assert.equal((await save()).deckLevel,1));
 assert.equal((await save()).deckLevel,2);assert.equal((await save()).plots.length,4);
 await page.getByRole('button',{name:/숲길 채집/}).click();
 const wood=(await save()).resources.wood;
 await chore(page.getByRole('button',{name:'나무 베러 가기',exact:true}),async()=>assert.equal((await save()).resources.wood,wood));
 assert.equal((await save()).resources.wood,wood+18);assert.equal((await save()).stats.chops,1);
 await page.getByRole('button',{name:'탐험',exact:true}).click();
 await chore(page.getByRole('button',{name:/버려진 휴게소/}));
 assert.equal((await save()).stats.gathers,1);
 await page.getByRole('button',{name:/사냥 나가기/}).click();
 const food=(await save()).resources.food;
 await page.locator('[data-start-hunt]').click();
 await page.locator('.battle-screen').waitFor();
 assert.ok((await save()).expedition);assert.equal((await save()).resources.food,food);
 await page.clock.runFor(1800);
 await page.getByRole('button',{name:'전투 일시정지',exact:true}).click();
 const pausedTime=await page.locator('[data-battle-time]').textContent();
 await page.clock.runFor(3000);assert.equal(await page.locator('[data-battle-time]').textContent(),pausedTime);
 await page.locator('[data-battle="resume"]').click();
 await page.locator('[data-skill="sweep"]').click();
 assert.equal(await page.locator('[data-skill="sweep"]').isDisabled(),true);
 await page.locator('[data-battle="auto"]').click();
 await page.screenshot({path:'artifacts/v0.2.0-mobile-battle.png'});
 for(let i=0;i<24;i++){
  if(await page.locator('[data-battle="finish"]').count())break;
  await page.clock.runFor(5000);
  assert.equal(await page.locator('.battle-screen').count(),1,'battle must remain open until return');
 }
 await page.locator('[data-battle="finish"]').waitFor();
 await page.screenshot({path:'artifacts/v0.2.0-battle-result.png'});
 await page.locator('[data-battle="finish"]').click();
 assert.equal((await save()).expedition,null);assert.equal((await save()).stats.battlesWon,1);
 assert.ok((await save()).resources.food>=food+8);
 assert.equal((await save()).stats.defeatedEnemies,8);
 assert.equal(await page.locator('#app').evaluate(el=>el.inert),false);
 const afterWin=await save();
 await page.reload();
 await page.locator('#resident-name').getByText('노을').waitFor();
 assert.equal((await save()).deckLevel,2);assert.equal((await save()).stats.battlesWon,1);assert.equal((await save()).resources.food,afterWin.resources.food);
 await page.getByRole('button',{name:/휴식하기/}).click();
 await page.getByRole('button',{name:/사냥 나가기/}).click();
 await page.locator('[data-start-hunt]').click();
 await page.clock.runFor(1000);
 const beforeRetreatFood=(await save()).resources.food;
 await page.locator('[data-battle="retreat"]').click();
 await page.locator('[data-battle="confirm-retreat"]').click();
 await page.clock.runFor(50);
 await page.locator('[data-battle="finish"]').click();
 assert.equal((await save()).expedition,null);assert.equal((await save()).stats.battlesWon,1);assert.equal((await save()).resources.food,beforeRetreatFood);
 await page.getByRole('button',{name:/우리집 작은 동료/}).click();
 await page.getByRole('button',{name:'보리 쓰다듬기',exact:true}).click();await close();
 await page.getByRole('button',{name:'설정',exact:true}).click();
 await page.getByRole('button',{name:'새 버전 확인',exact:true}).click();
 await page.getByText(/아직 배포 서버가 연결되지 않았어요/).waitFor();await close();
 await context.setOffline(true);
 await page.getByRole('button',{name:/휴식하기/}).click();
 assert.ok((await save()).energy>0);await context.setOffline(false);
 await page.clock.runFor(3500);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:'artifacts/v0.2.0-mobile-home.png',fullPage:true});
 // Simulate the exact older schema left by an installed v0.1 APK, then reopen it.
 await page.evaluate(()=>{
  const old=JSON.parse(localStorage.getItem('road-haven-save-v1'));
  delete old.expedition;delete old.stats.chops;delete old.stats.battlesWon;delete old.stats.defeatedEnemies;
  localStorage.setItem('road-haven-legacy-test-input',JSON.stringify(old));
 });
 await context.addInitScript(()=>{const legacy=localStorage.getItem('road-haven-legacy-test-input');if(legacy){localStorage.setItem('road-haven-save-v1',legacy);localStorage.removeItem('road-haven-legacy-test-input');}});
 await page.reload();
 await page.locator('#resident-name').getByText('노을').waitFor();
 await page.getByRole('button',{name:/휴식하기/}).click();
 assert.equal((await save()).deckLevel,2);assert.equal((await save()).stats.chops,0);assert.equal((await save()).expedition,null);
 // Interrupt an active expedition: one entry cost is kept; no reward is invented.
 await page.getByRole('button',{name:/사냥 나가기/}).click();await page.locator('[data-start-hunt]').click();
 const pending=await save();assert.ok(pending.expedition);
 await page.reload();await page.locator('#resident-name').getByText('노을').waitFor();
 assert.equal((await save()).expedition,null);assert.equal((await save()).resources.food,pending.resources.food);assert.equal((await save()).energy,pending.energy);
 await page.setViewportSize({width:1440,height:1100});await page.clock.runFor(4000);
 await page.screenshot({path:'artifacts/v0.2.0-desktop-home.png',fullPage:true});
 assert.deepEqual(errors,[]);
 console.log('PASS: mobile animated farming/woodcutting, delayed resource commits, deck expansion, 3-wave combat victory/skills/pause/retreat, exactly-once rewards, v0.1 save migration, interrupted expedition recovery, reload, offline actions, responsive layout and clean console.');
} catch(error) {
 await page.screenshot({path:'artifacts/v0.2.0-ui-failure.png',fullPage:true}).catch(()=>{});
 console.error('UI diagnostic',await page.locator('[data-battle-time]').textContent().catch(()=>null),await page.locator('[data-battle-wave]').textContent().catch(()=>null),errors);
 throw error;
} finally {await browser.close();}
