import { resourceLabels, type GameState, type Resource } from './game';
import { BUILDINGS, BUILDING_TYPES, getSettlement, getAllUnlockedSlots, getUpgradeCost, getProductionCost, formatProductionDuration, upgradeFacility, type Building, type BuildingType } from './settlement';
import { getTruckFloorCount, getSlotFloor, getSlotLocalIndex } from './truck-layout';
import { icon } from './icons';
import { facilityIcon } from './settlement-art';
import { getUnitBattleBonuses } from './units';

export const buildingNames:Record<BuildingType,string>={workshop:'도로 공방',kitchen:'마을 주방',waterworks:'빗물 정수소',greenhouse:'씨앗 온실',watchtower:'도로 관측소',petHouse:'동료의 쉼터'};
const slotLabel=(slot:number)=>`${getSlotFloor(slot)}층 · ${getSlotLocalIndex(slot)+1}번 자리`;
const amount=(state:GameState,r:Resource,n:number)=>`<span class="${state.resources[r]<n?'insufficient':''}">${icon(r)} ${n}</span>`;
const battleEffect=(state:GameState,type:BuildingType)=>{
 const bonus=getUnitBattleBonuses(state);
 return type==='petHouse'?`출전 동료 공격력 +${Math.round((bonus.attackMultiplier-1)*100)}%`:type==='watchtower'?`동료가 받는 피해 ${Math.round((1-bonus.enemyDamageMultiplier)*100)}% 감소`:'';
};
export function buildingCatalog(state:GameState){
 const settlement=getSettlement(state),used=settlement.buildings.length,slots=getAllUnlockedSlots(state);
 return `<p class="modal-description">시설을 고르고 트럭 위 빈 자리에 놓아 주세요.<br>Lv.5까지 개선하면 생산량과 속도가 함께 늘어나요.</p><div class="build-capacity">${icon('truck')} ${getTruckFloorCount(state)}층 · 데크 Lv.${state.deckLevel}<strong>시설 ${used} / ${slots}</strong><button data-open="expand">확장 ${icon('arrow')}</button></div><div class="building-edit-list" aria-label="완성된 건물 재배치"><button data-open="house">${icon('home')}<span>우리집<small>무료 재배치</small></span></button><button data-open="floors">${icon('expand')}<span>2·3층<small>증축하기</small></span></button>${settlement.buildings.map(building=>`<button data-facility-edit="${building.id}">${facilityIcon(building.type)}<span>${BUILDINGS[building.type].name}<small>${slotLabel(building.slot)} · 재배치</small></span></button>`).join('')}</div><div class="building-catalog">${BUILDING_TYPES.map(type=>{const b=BUILDINGS[type],locked=state.deckLevel<b.unlockLevel;return `<button class="building-card ${locked?'locked':''}" data-build-type="${type}" aria-label="${b.name} 건설 ${locked?`데크 ${b.unlockLevel}레벨 필요`:''}"><span class="building-card-art">${facilityIcon(type)}</span><span class="building-unlock">${locked?`데크 Lv.${b.unlockLevel}`:'건설 가능'}</span><strong>${b.name}</strong><span class="building-description">${b.description}</span><span class="building-output">${icon(b.yieldResource)} ${resourceLabels[b.yieldResource]} +${b.yieldAmount}<small> · ${formatProductionDuration({type,level:1})}</small></span><span class="building-cost">${amount(state,'wood',b.wood)}${amount(state,'scrap',b.scrap)}</span><span class="building-select">${locked?'미리 보기':'트럭 위에 배치'} ${icon('chevron')}</span></button>`;}).join('')}</div><p class="fine-print">빈 자리와 미리 보기를 확인한 후 건설 확정으로 재료를 사용해요.<br>생산 시간은 초 단위예요. 다른 일을 하는 동안에도 생산해요. 잠시 앱을 닫아도 생산 시간이 이어져요. 전투·일시정지 중에는 쉬어 갑니다.</p><button class="button button-light full-width activity-secondary" data-action="gather">${icon('map')} 부족한 건설 재료 찾기</button>`;
}
export function facilitySheet(state:GameState,building:Building){
 const b=BUILDINGS[building.type];
 return `<div class="facility-sheet-heading"><span class="facility-sheet-art">${facilityIcon(building.type,building.level)}</span><div><small>우리 트럭의 ${slotLabel(building.slot)} · ${formatProductionDuration(building)}마다 생산</small><h3>${b.name} <span data-facility-level>Lv.${building.level} / ${b.maxLevel}</span></h3></div><button class="sheet-close" data-facility-close aria-label="시설 선택 닫기">${icon('close')}</button></div><div class="facility-production"><span data-production-status></span><strong data-production-reward>${icon(b.yieldResource)} +${b.yieldAmount*building.level}</strong><div class="facility-progress"><i></i></div></div><div class="facility-sheet-actions"><button class="facility-primary" data-facility-start="${building.id}">${icon(b.yieldResource)}<span>생산 시작</span></button><button class="facility-primary collect" data-facility-collect="${building.id}" hidden>${icon('bag')}<span>생산품 수령</span></button><button class="facility-secondary" data-facility-upgrade="${building.id}"><span>${icon('hammer')}</span><small>${building.level>=b.maxLevel?'최대 레벨':`Lv.${building.level} → ${building.level+1}`}</small></button><button class="facility-secondary" data-facility-move="${building.id}"><span>${icon('expand')}</span><small>재배치</small></button><button class="facility-secondary" data-facility-replace="${building.id}"><span>${icon('truck')}</span><small>시설 교체</small></button></div><p class="facility-recipe">${b.recipe?Object.entries(b.recipe).map(([r,n])=>`${resourceLabels[r as Resource]} ${Number(n)*building.level}`).join(' · ')+' 사용':'재료 사용 없이 생산해요'} · 최대 Lv.${b.maxLevel}${battleEffect(state,building.type)?`<br>${battleEffect(state,building.type)} · 같은 시설은 최고 레벨만 적용`:''}</p>`;
}
/** A single explicit confirmation pays only the next level, with current stock visible. */
export function facilityUpgradePreview(state:GameState,building:Building):string{
 const b=BUILDINGS[building.type],next={...building,level:building.level+1},cost=getUpgradeCost(building);
 if(building.level>=b.maxLevel)return `<p class="modal-description">${b.name}은 최대 Lv.${b.maxLevel}이에요.</p>`;
 const recipe=(target:Building)=>Object.entries(getProductionCost(target)).map(([r,n])=>`${resourceLabels[r as Resource]} ${n}`).join(' · ')||'재료 없이 생산';
 const after=upgradeFacility(state,building.id).state;
 const bonus=battleEffect(state,building.type)?`<div class="cost-row" data-facility-upgrade-bonus><span>현재 전투 효과<strong>${battleEffect(state,building.type)}</strong></span><span>다음 레벨 전투 효과<strong>${battleEffect(after,building.type)}</strong></span></div><p class="fine-print">같은 시설 여러 곳은 가장 높은 레벨 하나만 적용해요.<br>새 효과는 다음 탐험을 출발할 때 적용돼요.</p>`:'';
 return `<div class="upgrade-facility-art">${facilityIcon(building.type,building.level)}${icon('arrow')}<strong>Lv.${building.level} → ${next.level}</strong></div><div class="cost-row" data-facility-upgrade-stats><span>한 번에 생산<strong>${b.yieldAmount*building.level} → ${b.yieldAmount*next.level}개</strong></span><span>생산 시간<strong>${formatProductionDuration(building)} → ${formatProductionDuration(next)}</strong></span></div><p class="fine-print">${resourceLabels[b.yieldResource]} 생산량이 늘고 더 빨리 완성돼요.<br>생산 재료: ${recipe(building)} → ${recipe(next)}</p>${bonus}<div class="cost-row"><span>${icon('wood')} 보유 목재 / 필요<strong>${state.resources.wood} / ${cost.wood}</strong></span><span>${icon('scrap')} 보유 고철 / 필요<strong>${state.resources.scrap} / ${cost.scrap}</strong></span></div><button class="button full-width" data-upgrade-confirm="${building.id}">${icon('hammer')} Lv.${next.level}로 한 단계 올리기</button>${state.resources.wood<cost.wood||state.resources.scrap<cost.scrap?`<button class="button button-light full-width activity-secondary" data-action="gather">${icon('map')} 부족한 개선 재료 찾기</button>`:''}<p class="fine-print">확정할 때 목재 ${cost.wood} · 고철 ${cost.scrap}을 사용해요.<br>생산 중이거나 수령하지 않은 물자가 있으면 먼저 받아 주세요.</p>`;
}
export function productionState(state:GameState,building:Building){
 const ready=building.readyAt!==null&&state.totalMinutes>=building.readyAt;
 const running=building.readyAt!==null&&!ready;
 const progress=building.readyAt===null||building.startedAt===null?0:Math.min(1,Math.max(0,(state.totalMinutes-building.startedAt)/(building.readyAt-building.startedAt)));
 const remaining=Math.max(0,(building.readyAt??state.totalMinutes)-state.totalMinutes);
 return {ready,running,progress,remaining};
}
